# Render.com deployment configuration for Mirai Backend

services:
  - type: web
    name: mirai-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Root directory is automatically set to 'backend' when you configure in Render dashboard